import { ScaledImage } from 'app/components/ScaledImage'
import { View as DView } from 'dripsy'
import { Image, StyleSheet } from 'react-native'
import { ButtonWithChildren } from '../../components/Button'
import Text from '../../components/Text'
import { Ionicons } from '@expo/vector-icons'
