server:
  port: 8082

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

spring:
  servlet:
    multipart:
      max-file-size: 5MB 
      max-request-size: 5MB 
  mvc:
    format:
      date-time: iso
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/society
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
  application:
    name: SOCIETY

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQL82Dialect
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              drop-source: metadata
              scripts:
                action: create
                create-target: META-INF/sql/create.sql
              database:
                action: drop-and-create
            sql-load-script-source: META-INF/sql/data.sql

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}

jwt:
  secret-key: ${JWT_SECRET:9y/B?E(H+KbPeShVmYq3t6w9z$C&F)J@}

static:
  location: ${STATIC_FILES_LOCATION:/tmp/public/}
