# TODO: Replace keys environment variables
spring:
  cloud:
    gateway:
      enabled: true
  application:
    name: GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

springdoc:
  swagger-ui:
    configUrl: /swagger-config.json

jwt:
  secret-key: ${JWT_SECRET:9y/B?E(H+KbPeShVmYq3t6w9z$C&F)J@}

static:
  location: ${STATIC_FILES_LOCATION:/tmp/public/}
