version: '3.8'

services:
  discovery:
    container_name: service-discovery
    build:
      context: ../discovery

  gateway:
    container_name: api-gateway
    build:
      context: ../gateway
    ports:
      - 8080:8080
    environment:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    ports:
      - 9002:80

  db:
    container_name: campusme-db
    image: postgres:14.5
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - ./volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql