version: '3.8'

services:
  discovery:
    container_name: service-discovery
    build:
      context: ../discovery
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  gateway:
    container_name: api-gateway
    build:
      context: ../gateway
    ports:
      - 8080:8080
    environment:
      EUREKA_HOST: http://discovery:8761/eureka
    depends_on:
      - discovery
    restart: unless-stopped

  society-svc:
    container_name: api-core
    build:
      context: ../society-svc
    environment:
      JWT_SECRET:
      EUREKA_HOST: http://discovery:8761/eureka
      POSTGRES_HOST:
      POSTGRES_PASSWORD:
    depends_on: 
      - db
      - discovery

  teams-svc:
    container_name: api-teams
    build:
      context: ../teams-svc
    environment:
      JWT_SECRET:
      EUREKA_HOST: http://discovery:8761/eureka
      POSTGRES_HOST:
      POSTGRES_PASSWORD:
    depends_on: 
      - db
      - discovery

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    ports:
      - 9002:80

  db:
    image: postgres:14.5
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - ./volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
