version: '3.8'

services:
  discovery:
    container_name: service-discovery
    build:
      context: ../discovery
    image: campusmecr.azurecr.io/discovery
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  gateway:
    container_name: api-gateway
    build:
      context: ../gateway
    image: campusmecr.azurecr.io/gateway
    ports:
      - 8080:8080
    environment:
      EUREKA_HOST: http://discovery:8761/eureka
      REDIS_HOST: redis
      REDIS_PORT: 6379
      STATIC_FILES_LOCATION: /public/
    volumes:
      - public:/public/
    depends_on:
      - discovery
    restart: unless-stopped

  society:
    container_name: society
    build:
      context: ../society
    image: campusmecr.azurecr.io/society
    environment:
      JWT_SECRET: '9y/B?E(H+KbPeShVmYq3t6w9z@C&F)J@'
      EUREKA_HOST: http://discovery:8761/eureka
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      STATIC_FILES_LOCATION: /public/
    volumes:
      - public:/public/
    depends_on:
      - db
      - discovery

  team:
    container_name: team
    build:
      context: ../team
    image: campusmecr.azurecr.io/team
    environment:
      JWT_SECRET: '9y/B?E(H+KbPeShVmYq3t6w9z@C&F)J@'
      EUREKA_HOST: http://discovery:8761/eureka
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
      - discovery

  security:
    container_name: security
    build:
      context: ../security
    image: campusmecr.azurecr.io/security
    environment:
      JWT_SECRET: '9y/B?E(H+KbPeShVmYq3t6w9z@C&F)J@'
      EUREKA_HOST: http://discovery:8761/eureka
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      STATIC_FILES_LOCATION: /public/
    volumes:
      - public:/public/
    depends_on: 
      - db
      - discovery

  db:
    build:
      context: ../db
    image: campusmecr.azurecr.io/db
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379


  notification-broker:
    container_name: notification-broker
    build:
      context: ../notification-broker
    image: campusmecr.azurecr.io/notification-broker
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  public:
