services:
  society:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ../society:/app
  team:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ../team:/app
    ports:
      - 8083:8083
