version: '3.8'

services:
  discovery:
    container_name: service-discovery
    build:
      context: ../discovery
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  gateway:
    container_name: api-gateway
    build:
      context: ../gateway
    ports:
      - 8080:8080
    environment:
      EUREKA_HOST: http://discovery:8761/eureka
      REDIS_HOST: redis
      REDIS_PORT: 6379
      STATIC_FILES_LOCATION: /public/
    volumes:
      - public:/public/
    depends_on:
      - discovery
    restart: unless-stopped

  society:
    container_name: society
    build:
      context: ../society
    environment:
      JWT_SECRET:
      EUREKA_HOST: http://discovery:8761/eureka
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST:
      POSTGRES_PASSWORD:
      STATIC_FILES_LOCATION: /public/
    volumes:
      - public:/public/
    depends_on:
      - db
      - discovery

  team:
    container_name: team
    build:
      context: ../team
    environment:
      JWT_SECRET:
      EUREKA_HOST: http://discovery:8761/eureka
      POSTGRES_HOST:
      POSTGRES_PASSWORD:
    depends_on:
      - db
      - discovery

  security:
    container_name: security
    build:
      context: ../security
    environment:
      JWT_SECRET:
      EUREKA_HOST: http://discovery:8761/eureka
      POSTGRES_HOST:
      POSTGRES_PASSWORD:
      STATIC_FILES_LOCATION: /public/
    volumes:
      - public:/public/
    depends_on: 
      - db
      - discovery

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    ports:
      - 9002:80

  db:
    build:
      context: ../db
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379


  notification-broker:
    container_name: notification-broker
    build:
      context: ../notification-broker
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  public:
