server:
  port: 8082
  contextPath: /admin
  servlet:
    contextPath: /admin
  tomcat:
    use-relative-redirects: true

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      ui:
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>CampusMe Dashboard</span>
        title: "CampusMe Admin"
        external-views:
          - label: Entities
            url: "/admin/entities"
            order: 1000
          - label: Swagger
            url: "/swagger-ui.html"
            order: 1001
        cache:
          no-cache: true
        cache-templates: false

  web:
    resources: # Static resources
      static-locations: 
        - file:${STATIC_FILES_LOCATION:/tmp/public/}
        - file:src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0

  mvc:
    static-path-pattern: /public/**

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/security
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}

  application:
    name: SECURITY

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQL82Dialect
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              drop-source: metadata
              scripts:
                action: create
                create-target: META-INF/sql/create.sql
              database:
                action: drop-and-create
            sql-load-script-source: META-INF/sql/data.sql

eureka:
  instance:
    hostname: security
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}

static:
  location: ${STATIC_FILES_LOCATION:/tmp/public/}
