CREATE DATABASE society;
CREATE DATABASE team;
CREATE DATABASE security;

GRANT ALL PRIVILEGES ON DATABASE team TO postgres;
GRANT ALL PRIVILEGES ON DATABASE society TO postgres;
GRANT ALL PRIVILEGES ON DATABASE security TO postgres;
